// src/app/shared/components/button/button.component.ts
import { Component, input, output } from '@angular/core';

export type ButtonVariant = 'primary' | 'secondary' | 'outline' | 'ghost';
export type ButtonSize = 'sm' | 'md' | 'lg';

@Component({
  selector: 'app-button',
  template: `
    <button
      [type]="type()"
      [disabled]="disabled() || loading()"
      [class]="getButtonClasses()"
      (click)="onClick($event)"
    >
      @if (loading()) {
        <span class="inline-block w-4 h-4 mr-2 border-2 border-current border-t-transparent rounded-full animate-spin"></span>
      }
      <ng-content></ng-content>
    </button>
  `,
  host: {
    class: 'inline-block'
  }
})
export class ButtonComponent {
  readonly variant = input<ButtonVariant>('primary');
  readonly size = input<ButtonSize>('md');
  readonly type = input<'button' | 'submit' | 'reset'>('button');
  readonly disabled = input<boolean>(false);
  readonly loading = input<boolean>(false);
  readonly fullWidth = input<boolean>(false);

  readonly buttonClick = output<MouseEvent>();

  onClick(event: MouseEvent): void {
    if (!this.disabled() && !this.loading()) {
      this.buttonClick.emit(event);
    }
  }

  getButtonClasses(): string {
    const base = 'inline-flex items-center justify-center font-medium rounded-lg transition-all duration-200 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#3B82F6] cursor-pointer disabled:opacity-50 disabled:cursor-not-allowed select-none';
    
    let variantClasses = '';
    switch (this.variant()) {
      case 'primary':
        variantClasses = 'bg-[var(--accent)] hover:bg-[var(--accent-hover)] text-white shadow-sm';
        break;
      case 'secondary':
        variantClasses = 'bg-[#1C1C21] hover:bg-[#242428] text-[var(--text-primary)] border border-[#242428]';
        break;
      case 'outline':
        variantClasses = 'bg-transparent hover:bg-[#1C1C21] text-[var(--text-primary)] border border-[#242428]';
        break;
      case 'ghost':
        variantClasses = 'bg-transparent hover:bg-[#1C1C21] text-[#A1A1AA] hover:text-[var(--text-primary)]';
        break;
    }

    let sizeClasses = '';
    switch (this.size()) {
      case 'sm':
        sizeClasses = 'px-3 py-1.5 text-xs';
        break;
      case 'md':
        sizeClasses = 'px-4 py-2 text-sm';
        break;
      case 'lg':
        sizeClasses = 'px-6 py-3 text-base';
        break;
    }

    const widthClass = this.fullWidth() ? 'w-full' : '';

    return `${base} ${variantClasses} ${sizeClasses} ${widthClass}`;
  }
}

// frontend/src/components/ui/button.jsx
import * as React from "react"
import { Slot } from "@radix-ui/react-slot"
import { cva } from "class-variance-authority";

import { cn } from "@/lib/utils"

const buttonVariants = cva(
  "inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-lg text-sm font-medium transition-all duration-300 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 [&_svg]:pointer-events-none [&_svg]:size-4 [&_svg]:shrink-0 font-space",
  {
    variants: {
      variant: {
        default: "bg-primary text-primary-foreground hover:bg-primary/90 shadow-glow hover:shadow-glow-lg",
        destructive:
          "bg-destructive text-destructive-foreground hover:bg-destructive/90",
        outline:
          "border border-border bg-transparent text-foreground hover:bg-primary/10 hover:border-primary/50",
        secondary:
          "bg-secondary text-secondary-foreground hover:bg-secondary/80",
        ghost: "hover:bg-primary/10 hover:text-primary text-foreground",
        link: "text-primary underline-offset-4 hover:underline",
        // Custom variants
        cyber: "bg-gradient-to-r from-primary to-accent text-primary-foreground hover:shadow-glow-lg font-semibold",
        glass: "glass-card text-foreground hover:border-primary/40",
      },
      size: {
        default: "h-10 px-6 py-2",
        sm: "h-9 rounded-md px-4",
        lg: "h-12 rounded-lg px-8 text-base",
        xl: "h-14 rounded-lg px-10 text-lg",
        icon: "h-10 w-10",
      },
    },
    defaultVariants: {
      variant: "default",
      size: "default",
    },
  }
)

const Button = React.forwardRef(({ className, variant, size, asChild = false, ...props }, ref) => {
  const Comp = asChild ? Slot : "button"
  return (
    (<Comp
      className={cn(buttonVariants({ variant, size, className }))}
      ref={ref}
      {...props} />)
  );
})
Button.displayName = "Button"

export { Button, buttonVariants }
